dist: trusty
sudo: required

language: node_js

node_js:
  - "7"

cache:
 - node_modules

install:
 - npm install

script:
 - npm test
 - npm run dist

notifications:
  slack: biobright:6j8QQyUUSW9mXJPSKPzGnZM4
    on_success: always
    on_failure: always
  email:
    - ranganath@biobright.org
