# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6

    steps:
      - checkout
      - run:
         command: |
            echo "Start"
            node --version
            npm -v
            npm install
            npm config set loglevel warn
            npm config get loglevel
            npm test
      - run: npm run dist

  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: Test
          command: |
            npm config set loglevel warn
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
